[package]
name = "mesh_infer_database"
version = "0.1.0"
edition = "2024"

[dependencies]

anyhow = "1.0.102"
loro = "1.12.0"
mimalloc = "0.1.50"

iceoryx2-log = { workspace = true, features = ["std"] }
iceoryx2-services-discovery = { workspace = true, features = ["std"] }
iceoryx2 = { workspace = true, features = ["std"] }
iceoryx2-cal = { workspace = true, features = ["std"] }
iceoryx2-bb-loggers = { workspace = true, features = ["std", "console"]}
iceoryx2-bb-concurrency = { workspace = true, features = ["std"] }
iceoryx2-bb-container = { workspace = true, features = ["std"] }
iceoryx2-bb-derive-macros = { workspace = true, features = ["std"] }
iceoryx2-bb-elementary = { workspace = true, features = ["std"] }
iceoryx2-bb-elementary-traits = { workspace = true }
iceoryx2-bb-system-types = { workspace = true, features = ["std"] }
iceoryx2-bb-posix = { workspace = true, features = ["std"] }
