* Goals

** Check fully static builds

** Main structs:

*** =standalone_chunk=:
  1. Hold the data along with the hash.

*** =metadata_chunk=:
  1. Hold metadata (hash, size) of the chunk for future retrieval.
  2. Read the file and provide the data.

*** =hashed_chunk=:
  1. Hash the chunks.
  2. Write out the chunks into files.

*** =metadata_file=:
  1. Read the file and do the chunk splitting.
  2. Hand over the chunks for writing.

** Split =input file= into chunks and metadata [p1(hash, size), p2(hash, size), ...] :DONE:
_INPUT_: ~file_path~, ~output_prefix_directory_path~
_OUTPUT_: ~table~
_EFFECT_:
    1. Write ~chunk~ inside ~output_prefix_directory_path~
*** Implementation details
1. =metadata_file::open=:
    _INPUT_: ~file_path~, ~max_size_per_chunk~.
    _OUTPUT_: ~metadata_file~
   - Maps the input file into memory.
   - Calculates the number of chunks.
2. =metadata_file::write_file_to_prefix=:
    _INPUT_: ~output_prefix_directory_path~
    _OUTPUT_: ~table~
    _EFFECT_: Write chunks to files under prefix
   - Actually force chunks into memory using =madvise= and hashing.
   - write it out to file using =hashed_chunk= as intermediates.
   - Return the metadata needed to reconstruct the file.

** Implement reading each chunk from the store.
_INPUT_: ~table~
_OUTPUT_: ~file_generator~

- =metadata_chunk::read_from_prefix= implements the reading from 1 chunk.

  

* Cargo.toml

** Basic headers
#+begin_src conf :mkdirp yes :tangle ./Cargo.toml
  [package]
  name = "mesh_infer_database"
  version = "0.1.0"
  edition = "2024"
#+end_src

** Dependencies
#+begin_src conf :mkdirp yes :tangle ./Cargo.toml
  [dependencies]
  anyhow = "1"
  blake3 = { version = "1", features = ["mmap", "rayon", "serde"] }
  inotify = "0.11"
  loro = "1"
  memmap2 = "0.9"
  mimalloc = "0.1"
  tokio = { version = "1", features = ["full"] }
#+end_src

* Script to build

** Regular

*** Debug
#+begin_src sh :shebang #!/bin/sh :results output :mkdirp yes :tangle ./build/debug.sh
  cd "$(dirname -- "${0}")/.."

  cargo build
#+end_src

*** Optimized
#+begin_src sh :shebang #!/bin/sh :results output :mkdirp yes :tangle ./build/release.sh
  cd "$(dirname -- "${0}")/.."

  cargo build --release
#+end_src

* Main rust code

** struct for inotify related file alerting
#+begin_src rust :mkdirp yes :tangle ./src/dir_watcher/mod.rs
  pub struct dir_watcher {
      notify: inotify::Inotify,
      watchdescriptor: inotify::WatchDescriptor,
      buffer: Vec<u8>,
      path_dir_prefix_input: std::path::PathBuf,
      first_run: bool,
  }

  impl dir_watcher {
      pub fn new(path_dir_prefix_input: impl AsRef<std::path::Path>) -> anyhow::Result<Self> {
          let notify = inotify::Inotify::init()?;

          let watchdescriptor = notify.watches().add(
              path_dir_prefix_input.as_ref(),
              inotify::WatchMask::ATTRIB
                  | inotify::WatchMask::CREATE
                  | inotify::WatchMask::CLOSE_WRITE
                  | inotify::WatchMask::CLOSE_NOWRITE
                  | inotify::WatchMask::MOVED_TO,
          )?;

          Ok(Self {
              notify: notify,
              watchdescriptor: watchdescriptor,
              buffer: vec![0; 1 << 21],
              path_dir_prefix_input: path_dir_prefix_input.as_ref().to_path_buf(),
              first_run: true,
          })
      }

      fn get_all_files(
          &mut self,
          ret: &mut std::collections::HashSet<std::path::PathBuf>,
      ) -> anyhow::Result<()> {
          ret.extend(
              std::fs::read_dir(&self.path_dir_prefix_input)?.filter_map(|entry| {
                  entry
                      .map(|e| e.path())
                      .map_err(|e| eprintln!("Failed to read file: {}", e))
                      .ok()
              }),
          );

          Ok(())
      }

      fn get_new_files(
          &mut self,
          ret: &mut std::collections::HashSet<std::path::PathBuf>,
      ) -> anyhow::Result<()> {
          ret.extend(
              self.notify
                  .read_events_blocking(self.buffer.as_mut_slice())?
                  .into_iter()
                  .map(|event| event.name)
                  .flatten()
                  .map(|name| self.path_dir_prefix_input.join(name)),
          );

          Ok(())
      }

      fn get_new_files_immediate(
          &mut self,
          ret: &mut std::collections::HashSet<std::path::PathBuf>,
      ) -> anyhow::Result<()> {
          ret.extend(
              self.notify
                  .read_events(self.buffer.as_mut_slice())?
                  .into_iter()
                  .map(|event| event.name)
                  .flatten()
                  .map(|name| self.path_dir_prefix_input.join(name)),
          );

          Ok(())
      }

      fn look_start(
          &mut self,
          ret: &mut std::collections::HashSet<std::path::PathBuf>,
      ) -> anyhow::Result<()> {
          if self.first_run {
              self.get_all_files(ret)?;
              self.first_run = false;
          } else {
              self.get_new_files(ret)?;
          }

          Ok(())
      }

      fn look_more(
          &mut self,
          ret: &mut std::collections::HashSet<std::path::PathBuf>,
          timeout: std::time::Duration,
          batch_size: usize,
          mut num_retries: u8,
      ) -> anyhow::Result<()> {
          let start_time = std::time::Instant::now();

          while (ret.len() < batch_size) && (start_time.elapsed() < timeout) && (num_retries > 0) {
              match self.get_new_files_immediate(ret) {
                  Ok(_) => {
                      num_retries -= 1;
                  }
                  Err(_) => {}
              }
          }

          Ok(())
      }

      fn get_batch(
          &mut self,
          ret: &mut std::collections::HashSet<std::path::PathBuf>,
          timeout: std::time::Duration,
          batch_size: usize,
          num_retries: u8,
      ) -> anyhow::Result<()> {
          self.look_start(ret)?;

          self.look_more(
              /*ret: &mut std::collections::HashSet<std::path::PathBuf> =*/ ret,
              /*timeout: std::time::Duration =*/ timeout,
              /*batch_size: usize =*/ batch_size,
              /*mut num_retries: u8 =*/ num_retries,
          )?;

          Ok(())
      }

      pub fn get_files(
          &mut self,
          timeout: std::time::Duration,
          batch_size: usize,
          num_retries: u8,
      ) -> anyhow::Result<std::collections::HashSet<std::path::PathBuf>> {
          let mut ret: std::collections::HashSet<std::path::PathBuf> =
              std::collections::HashSet::new();

          self.get_batch(
              /*ret: &mut std::collections::HashSet<std::path::PathBuf> =*/ &mut ret,
              /*timeout: std::time::Duration =*/ timeout,
              /*batch_size: usize =*/ batch_size,
              /*mut num_retries: u8 =*/ num_retries,
          )?;

          return Ok(ret);
      }
  }
#+end_src

** Code for file blob

*** Code for chunks
#+begin_src rust :mkdirp yes :tangle ./src/file_blobs/chunk_worker/mod.rs
  use std::io::{Read, Write};

  #[inline(always)]
  fn construct_name(
      path_dir_prefix: impl AsRef<std::path::Path>,
      hash: &blake3::Hash,
      size: usize,
      create_dir: bool,
  ) -> anyhow::Result<std::path::PathBuf> {
      let res = hash.to_hex().to_string();

      let tmp = path_dir_prefix
          .as_ref()
          .join(&res[0..2])
          .join(&res[2..4])
          .join(&res);

      if create_dir {
          std::fs::create_dir_all(&tmp)?;
      }

      Ok(tmp.join(format!("{:x}", size)))
  }

  pub struct standalone_chunk<'a> {
      pub chunk: Vec<u8>,
      pub hash: &'a blake3::Hash,
  }

  pub struct metadata_chunk {
      pub hash: blake3::Hash,
      pub size: usize,
  }

  pub struct hashed_chunk<'a> {
      pub chunk: &'a [u8],
      pub hash: blake3::Hash,
  }

  impl metadata_chunk {
      #[inline(always)]
      pub fn read_from_prefix(
          &self,
          path_dir_prefix: impl AsRef<std::path::Path>,
      ) -> anyhow::Result<Vec<u8>> {
          Ok(std::fs::read(construct_name(
              /*path_dir_prefix: impl AsRef<std::path::Path> =*/ path_dir_prefix,
              /*hash: &blake3::Hash =*/ &self.hash,
              /*size: usize =*/ self.size,
              /*create_dir: bool =*/ false,
          )?)?)
      }
  }

  impl<'a> hashed_chunk<'a> {
      pub fn new(chunk: &'a [u8]) -> Self {
          let hash = blake3::hash(chunk);
          Self { chunk, hash }
      }

      pub fn write_to_destination(
          &self,
          path_dir_prefix: impl AsRef<std::path::Path>,
      ) -> anyhow::Result<metadata_chunk> {
          std::fs::File::create(construct_name(
              /*path_dir_prefix: impl AsRef<std::path::Path> =*/ &path_dir_prefix,
              /*hash: &blake3::Hash =*/ &self.hash,
              /*size: usize =*/ self.chunk.len(),
              /*create_dir: bool =*/ true,
          )?)?
          .write_all(self.chunk)?;

          Ok(metadata_chunk {
              hash: self.hash.clone(),
              size: self.chunk.len(),
          })
      }
  }

  impl<'a> standalone_chunk<'a> {
      pub fn from(
          element: &'a metadata_chunk,
          path_dir_prefix: impl AsRef<std::path::Path>,
      ) -> anyhow::Result<Self> {
          return Ok(Self {
              chunk: element.read_from_prefix(&path_dir_prefix)?,
              hash: &element.hash,
          });
      }

      pub fn append_to_file(&self, fd: &mut std::fs::File) -> anyhow::Result<()> {
          fd.write_all(self.chunk.as_ref())?;
          Ok(())
      }
  }

#+end_src

*** Code for the class which chunks and hashes each file
#+begin_src rust :mkdirp yes :tangle ./src/file_blobs/mod.rs
  mod chunk_worker;

  use chunk_worker::*;

  pub fn write_table_2_file(
      tables_input: &Vec<metadata_chunk>,
      path_dir_prefix_input: impl AsRef<std::path::Path>,
      path_file_output: impl AsRef<std::path::Path>,
  ) -> anyhow::Result<()> {
      let mut fd = std::fs::File::create(/*path =*/ path_file_output.as_ref())?;

      for i in tables_input.iter() {
          standalone_chunk::from(&i, path_dir_prefix_input.as_ref())?.append_to_file(&mut fd)?;
      }

      return Ok(());
  }

  pub struct metadata_file {
      fd: std::fs::File,
      mmap: memmap2::Mmap,
      size_piece: usize,
      n_pieces: usize,
  }

  impl metadata_file {
      pub fn open(
          path_file_input: impl AsRef<std::path::Path>,
          size_piece_pw: usize,
      ) -> anyhow::Result<Self> {
          let fd = std::fs::File::open(path_file_input)?;

          let size_piece = 1 << size_piece_pw;
          let size_piece_mask = size_piece - 1;

          let mmap = unsafe { memmap2::Mmap::map(&fd) }?;
          mmap.advise(memmap2::Advice::Sequential)?;

          let n_pieces = {
              let q = mmap.len() >> size_piece_pw;
              let r = mmap.len() & size_piece_mask;
              if r == 0 { q } else { q + 1 }
          };

          Ok(Self {
              fd: fd,
              mmap: mmap,
              size_piece: size_piece,
              n_pieces: n_pieces,
          })
      }

      pub fn write_file_to_prefix(
          &self,
          path_dir_prefix: impl AsRef<std::path::Path>,
      ) -> anyhow::Result<Vec<metadata_chunk>> {
          const read_ahead: usize = 1 << 3;
          const read_mask: usize = read_ahead - 1;

          let mut ret: Vec<metadata_chunk> = Vec::with_capacity(self.n_pieces);

          for idx in 0..self.n_pieces {
              let start = idx * self.size_piece;

              if (idx & read_mask) == 0 {
                  let stop = (start + ((read_ahead << 1) * self.size_piece)).min(self.mmap.len());

                  self.mmap
                      .advise_range(memmap2::Advice::WillNeed, start, stop - start)?;
              }

              let stop = (start + self.size_piece).min(self.mmap.len());

              let res = &self.mmap[start..stop];
              let piece = hashed_chunk::new(res);
              let out_data = piece.write_to_destination(path_dir_prefix.as_ref())?;
              ret.push(out_data);
          }

          Ok(ret)
      }
  }
#+end_src

** The main code
#+begin_src rust :mkdirp yes :tangle ./src/main.rs
  #[global_allocator]
  static GLOBAL: mimalloc::MiMalloc = mimalloc::MiMalloc;

  use std::any::Any;

  mod dir_watcher;
  mod file_blobs;

  fn dir_watcher_main() -> anyhow::Result<()> {
      let mut watched = dir_watcher::dir_watcher::new("/dev/shm".to_string())?;
      loop {
          for i in watched.get_files(std::time::Duration::from_millis(100), 16, 1)? {
              eprintln!("Found file {}", i.to_str().unwrap_or("NO PATH FOUND"));
          }
      }
      return Ok(());
  }

  fn main() -> anyhow::Result<()> {
      let res = file_blobs::metadata_file::open("./video.mp4", 16)?;
      let tmp = res.write_file_to_prefix(
          /*path_dir_prefix: &std::path::Path =*/ "/home/asd/dest",
      )?;
      tmp.iter().for_each(|i| {
          println!(
              "{}: {}",
              i.hash.to_hex().as_str(),
              i.size.to_string().as_str()
          );
      });

      file_blobs::write_table_2_file(
          /*tables_input: Vec<metadata_chunk> =*/ &tmp,
          /*path_dir_prefix_input: impl AsRef<std::path::Path> =*/ "/home/asd/dest",
          /*path_file_output: impl AsRef<std::path::Path> =*/ "./new.mp4",
      )?;

      Ok(())
  }
#+end_src

* GIT Scripts

** Ignore

*** List
#+begin_src conf :mkdirp yes :tangle ./GIT/ignore.list
  /Cargo.lock
  /target/
  /src/watch.rs
  /dest/
#+end_src

*** Script
#+begin_src sh :shebang #!/bin/sh :results output :mkdirp yes :tangle ./GIT/ignore.sh
  cd "$(dirname -- "${0}")/.."
  (cat './GIT/ignore.list' ; sed 's@^@/@g' './GIT/rm.list') > './.gitignore'
#+end_src

** To remove

*** List
#+begin_src conf :mkdirp yes :tangle ./GIT/rm.list
  #Cargo.toml#
  .#README.org
  README.org~
  tmp.sh
#+end_src

*** Script
#+begin_src sh :shebang #!/bin/sh :results output :mkdirp yes :tangle ./GIT/rm.sh
  cd "$(dirname -- "${0}")/.."
  sed 's@^@"./@g ; s@$@"@g' './GIT/rm.list' | tr '\n' ' ' | sed 's@^@"rm" "-vf" "--" @g' | sh
#+end_src

** To add

*** list
#+begin_src conf :mkdirp yes :tangle ./GIT/add.list
  build/debug.sh
  build/release.sh
  Cargo.toml
  GIT/add.list
  GIT/add.sh
  GIT/commit_and_push.sh
  .gitignore
  GIT/ignore.list
  GIT/ignore.sh
  GIT/rm.list
  GIT/rm.sh
  GIT/update.sh
  README.org
  src/dir_watcher/mod.rs
  src/file_blobs/chunk_worker/mod.rs
  src/file_blobs/mod.rs
  src/main.rs
#+end_src

*** Script
#+begin_src sh :shebang #!/bin/sh :results output :mkdirp yes :tangle ./GIT/add.sh
  cd "$(dirname -- "${0}")/.."
  git add '--pathspec-from-file=./GIT/add.list'
#+end_src

** Do both
#+begin_src sh :shebang #!/bin/sh :results output :mkdirp yes :tangle ./GIT/update.sh
  cd "$(dirname -- "${0}")"
  ./rm.sh
  ./ignore.sh
  ./add.sh
  cd '../'
  git status
#+end_src

** Commit and push
#+begin_src sh :shebang #!/bin/sh :results output :mkdirp yes :tangle ./GIT/commit_and_push.sh
  cd "$(dirname -- "${0}")/.."
  "${HOME}/SSH/K/P/setup.sh"
  git commit -m 'Started some cleanups and reorg'
  git push
#+end_src

** COMMENT Run the script

*** Add and status
#+begin_src emacs-lisp :results silent
  (save-buffer)
  (org-babel-tangle)
  (async-shell-command "
      './GIT/update.sh'
  " "log" "err")
#+end_src

*** Commit and push
#+begin_src emacs-lisp :results silent
  (async-shell-command "
      './GIT/commit_and_push.sh'
  " "log" "err")
#+end_src

      #[inline(always)]
      pub fn get_len(&self) -> usize {
          self.mmap.len()
      }

      #[inline(always)]
      pub fn get_n_pieces(&self) -> usize {
          self.n_pieces
      }

      pub fn get_piece(&self, idx: usize) -> anyhow::Result<&[u8]> {
          if idx >= self.n_pieces {
              return Err(anyhow::format_err!("Index out of bounds..."));
          }
          let start = idx * self.size_piece;
          let stop = (start + self.size_piece).min(self.mmap.len());

          self.mmap
              .advise_range(memmap2::Advice::WillNeed, start, stop - start)?;

          let res = &self.mmap[start..stop];
          return Ok(res);
      }

      pub fn get_all_chunks(&self) -> Vec<metadata_chunk<'_>> {
          self.mmap
              .chunks(self.size_piece)
              .map(|slice| metadata_chunk::new(slice))
              .collect()
      }
